//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitchenBook.MVVM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KitchenBookEntities : DbContext
    {
        public KitchenBookEntities()
            : base("name=KitchenBookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Recipe> Recipe { get; set; }
        public virtual DbSet<Recipes> Recipes { get; set; }
        public virtual DbSet<SecretInfo> SecretInfo { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersRecipes> UsersRecipes { get; set; }
    }
}
