//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitchenBook.MVVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersRecipes
    {
        public int ID_Like { get; set; }
        public int ID_User { get; set; }
        public int ID_recipe { get; set; }
    
        public virtual Recipes Recipes { get; set; }
        public virtual Users Users { get; set; }
    }
}
